name: Thagod Dynasty site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    - name: Build the site in the  thagoddynasty/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/thagoddynasty -v ${{ github.workspace }}/_site:/srv/thagoddynasty/_site \
        thagoddynasty/builder:latest /bin/bash -c "chmod -R 777 /srv/thagoddynasty && thagoddynasty build --future"
